### ISSUE TITLE
Sparkle fails to link when loaded by ghc

### ISSUE THREAD

**Issue by facundominguez** [LeapYear/sparkle#11] opened 2016-11-24 14:12 UTC
To reproduce:
```
cd sparkle
git checkout fd/linking-example
stack --nix install linking
```
The last step should produce
```
...
[1 of 1] Compiling Linking          ( Linking.hs, .stack-work/dist/x86_64-linux-nix/Cabal-1.22.5.0/build/Linking.o )
<command line>: can't load .so/.DLL for: /home/facundo/tweag/leapyear/sparkle/.stack-work/install/x86_64-linux-nix/lts-6.21/7.10.3/lib/x86_64-linux-ghc-7.10.3/sparkle-0.3-LgQLArXRhaP2u3ALJnjlMT/libHSsparkle-0.3-LgQLArXRhaP2u3ALJnjlMT-ghc7.10.3.so (/home/facundo/tweag/leapyear/sparkle/.stack-work/install/x86_64-linux-nix/lts-6.21/7.10.3/lib/x86_64-linux-ghc-7.10.3/sparkle-0.3-LgQLArXRhaP2u3ALJnjlMT/libHSsparkle-0.3-LgQLArXRhaP2u3ALJnjlMT-ghc7.10.3.so: undefined symbol: main)
Completed 5 action(s).

--  While building package linking-0.1 using:
      /home/facundo/.stack/setup-exe-cache/x86_64-linux-nix/setup-Simple-Cabal-1.22.5.0-ghc-7.10.3 --builddir=.stack-work/dist/x86_64-linux-nix/Cabal-1.22.5.0 build lib:linking exe:sparkle-example-linking --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure 1
```

There is an alternative to using template haskell, that also prods GHC to load `sparkle` while building other code. This is using ANN pragmas. For instance:
```
module Linking where

{-# ANN f True #-}
f :: IO ()
f = return ()
```
Replace the `Linking` module in the minimal example with the one provided above, and you should get the same error.

The branch is here: https://github.com/LeapYear/sparkle/compare/master...LeapYear:fd/linking-example

cc @robinbb @mboes

**Comment by robinbb** [comment] 2016-11-25 03:12
Assuming that the issue is fixed by #12.

**Closed by robinbb** 2016-11-25 03:12 UTC
